#! /bin/csh -f
#
#       script to generate crd files from pdb files using simulaid
#
       foreach v (`cat list`)
        echo $v
        set psf = `echo $v:r`-psf
        set psf2 = $psf.pdb
        set menv = `echo $psf:r`.menv
        set crd  = `echo $psf:r`.crd
        set out = `echo $psf:r`.out
        set newmenv = `echo $v:r`-new.menv
        cp $v temp
/home/bits/menv-source1/scripts/psfgen /home/bits/menv-source1/scripts/psf-pdb-gen-standalone.tcl $v $psf
set atomnum = `grep "ATOM" $psf2 | wc | awk '{print $1}'`
/home/bits/menv-source1/scripts/psfpdb-crd-conv2 $psf2 $crd $atomnum
/home/bits/menv-source1/exec/micro_debug_<<fin>$out
CHM
$crd
/home/bits/menv-source1/data/esp_all_env_allradii.dat
/home/bits/menv-source1/data/smenv_allh.dat
$menv
fin
/home/bits/menv-source1/scripts/ssbond.exe < $crd
foreach v2 ( `cat num` )
echo $v2
sed s/"$v2,  CYS,       2,  TO,"/"$v2,  CYS,       2,  TD,"/ $menv >temp2
cp temp2 $menv
sh /home/bits/menv-source1/scripts/newrenumber.sh $v $menv
#python working-files/plotting.py $newmenv
end
end
end
